# Generated by Django 3.1.5 on 2021-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
